server:
  port: 8022
  servlet:
    context-path: /user-server
eureka:
  instance:
    metadata-map:
      zone: China
  client:
    region: SpringCloud
#    prefer-same-zone-eureka: true
    availability-zones:
      SpringCloud: China,USA
    service-url:
      China: http://localhost:8082/eureka-server/eureka,http://localhost:8081/eureka-server/eureka
      USA: http://localhost:8083/eureka-server/eureka
    register-with-eureka: true
