spring:
  application:
    name: user-server
#  servlet:
#    context-path: /user-server
  sleuth:
    sampler:
      probability: 1.0
#    baggage-keys:
#      - foo
#      - bar
#    propagation-keys:
#      - foo
#      - bar
    log:
      slf4j:
        whitelisted-mdc-keys:
          - foo
          - bar
  zipkin:
    base-url: http://localhost:9411
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud_practice_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: root
  security:
    user:
      name: root
      password: root

mybatis:
  mapper-locations:
    - mapper/*.xml

eureka:
  instance:
    instance-id: ${spring.application.userName}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true

com:
  xufq:
    enable-controller-log: true
    enable-service-span: true