spring:
  application:
    name: user-server
#  servlet:
#    context-path: /user-server
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true