spring:
  application:
    name: user-server
#  servlet:
#    context-path: /user-server
  sleuth:
    sampler:
      probability: 1.0
#    baggage-keys:
#      - foo
#      - bar
#    propagation-keys:
#      - foo
#      - bar
    log:
      slf4j:
        whitelisted-mdc-keys:
          - foo
          - bar
  zipkin:
    base-url: http://localhost:9411
  datasource:
    hikari:
      maximum-pool-size: 5
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud_practice_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: root
mybatis:
  mapper-locations:
    - mapper/*.xml

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true

com:
  xufq:
    enable-controller-log: true
    enable-service-span: true
    login:
      basic:
        user-name: loginserver
        password: loginserver
    security:
      basic:
        user-name: userserver
        password: userserver
#      not-filter-urls: /user/**,/product/**
      token:
        validate-expired: false