spring:
  application:
    name: zuul-server
  cloud:
    config:
      enabled: false
server:
  servlet:
    context-path: /zuul-server
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.userName}:${spring.cloud.client.ip-address}:${server.port}
zuul:
  routes:
    product-server:
      path: /productserver/**
      serviceId: product-server
#      url: http://www.nginxserver.com:8080
      stripPrefix: true
#  ignored-services: '*'
  prefix: /api
  retryable: true
product-server:
  ribbon:
#    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
#    listOfServers: http://example1.com,http://example2.com
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100
management:
  endpoints:
    web:
      exposure:
        include: '*'
