spring:
  application:
    name: eureka-server
server:
  servlet:
    context-path: /eureka-server
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
#  server:
#    enable-self-preservation: false

