server:
  port: 8083
eureka:
  instance:
    metadata-map:
      zone: USA
  client:
    region: SpringCloud
    availability-zones:
      SpringCloud: USA,China
    service-url:
      China: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8081/${server.servlet.context-path}/eureka,http://${spring.security.user.name}:${spring.security.user.password}@localhost:8082/${server.servlet.context-path}/eureka
      USA: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8083/${server.servlet.context-path}/eureka
