server:
  port: 8888
  servlet:
    context-path: /eureka-server

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:${server.port}/${spring.application.name}/eureka
  server:
    enable-self-preservation: false

spring:
  application:
    name: eureka-server
