spring:
  application:
    name: eureka-server
  security:
    user:
      name: root
      password: root

server:
  servlet:
    context-path: /eureka-server

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
#  server:
#    enable-self-preservation: false

