server:
  port: 8014
eureka:
  instance:
    metadata-map:
      zone: China
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
  client:
    #    prefer-same-zone-eureka: true
    region: SpringCloud
    availability-zones:
      SpringCloud: China,USA
    service-url:
      China: http://root:root@localhost:8081/eureka-server/eureka,http://root:root@localhost:8082/eureka-server/eureka
      USA: http://root:root@localhost:8083/eureka-server/eureka
    registry-fetch-interval-seconds: 30 # 从Eureka Server刷新注册列表的间隔